In [1]:
import numpy as np


In [1]:
arr = np.arange(11)

NameError: name 'np' is not defined

In [2]:
arr

NameError: name 'arr' is not defined

In [4]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [5]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [6]:
A=np.random.randn(10)
A

array([-1.17695066, -1.00920651,  1.04054284,  1.74830234,  0.3241642 ,
        1.32970305,  0.24891081, -0.50339008, -0.52447292, -0.50695678])

In [7]:
B = np.random.randn(10)
B

array([-0.08474247,  0.38462414, -1.03594077, -0.03970053, -1.44108368,
       -1.95510628, -0.33299092, -1.58083619,  0.41370147, -0.88561536])

In [8]:
np.add(A,B)

array([-1.26169312, -0.62458236,  0.00460207,  1.70860181, -1.11691949,
       -0.62540323, -0.08408011, -2.08422627, -0.11077145, -1.39257215])

In [10]:
np.maximum(A,B)

array([-0.08474247,  0.38462414,  1.04054284,  1.74830234,  0.3241642 ,
        1.32970305,  0.24891081, -0.50339008,  0.41370147, -0.50695678])

In [11]:
#For full and extensive list of all universal functions
website = "http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs"
import webbrowser
webbrowser.open(website)

True

In [13]:
webbrowser.open(website)

True