In [1]:
import numpy as np


In [6]:
arr = np.arange(5)

In [8]:
np.save('my_array',arr)

In [27]:
arr2 = np.arange(9)
arr2


array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [28]:
np.load('my_array.npy')

array([0, 1, 2, 3, 4])

In [29]:
np.savez('two_arrayszip',x=arr,y=arr2)

In [30]:
archive_array = np.load('two_arrayszip.npz')

In [31]:
archive_array['x']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
archive_array['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [33]:
rm my_array.npy

In [34]:
rm two_arrayszip.npy

rm: two_arrayszip.npy: No such file or directory


In [35]:
arr = np.array([[1,2,3],[4,5,6]])

In [38]:
np.savetxt('my_array_txt.txt',arr,delimiter=',')

In [39]:
arr = np.loadtxt('my_array_txt.txt',delimiter=',')
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])