In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
arr1 = np.arange(9).reshape((3,3))

In [3]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [6]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
ser1 = Series([1,2,3],index=['A','B','C'])
ser2 = Series([4,5],index=['D','E'])

In [9]:
pd.concat([ser1,ser2])

A    1
B    2
C    3
D    4
E    5
dtype: int64

In [10]:
pd.concat([ser1,ser2],axis=1)

0   1
A   1 NaN
B   2 NaN
C   3 NaN
D NaN   4
E NaN   5

In [12]:
pd.concat([ser1,ser2],axis=1,join_axes=[['A','D','E']])

0   1
A   1 NaN
D NaN   4
E NaN   5

In [13]:
pd.concat([ser1,ser2],keys=['cat1','dog1'])

cat1  A    1
      B    2
      C    3
dog1  D    4
      E    5
dtype: int64

In [14]:
pd.concat([ser1,ser2],axis=1,keys=['cat1','dog1'])

cat1  dog1
A     1   NaN
B     2   NaN
C     3   NaN
D   NaN     4
E   NaN     5

In [15]:
dframe1 = DataFrame(np.random.randn(4,3), columns=['X', 'Y', 'Z'])
dframe2 = DataFrame(np.random.randn(3, 3), columns=['Y', 'Q', 'X'])

In [16]:
pd.concat([dframe1,dframe2])

Q         X         Y         Z
0       NaN -0.409204 -2.288672 -0.035896
1       NaN  0.417145 -1.210749 -1.353317
2       NaN -1.515640 -0.479633  1.718319
3       NaN  0.469202  0.761060  0.168241
0  0.678039  1.147087 -1.511676       NaN
1  1.997421  0.010971 -0.642358       NaN
2  0.200343 -1.243802  1.394458       NaN

In [17]:
pd.concat([dframe1,dframe2],ignore_index=True)

Q         X         Y         Z
0       NaN -0.409204 -2.288672 -0.035896
1       NaN  0.417145 -1.210749 -1.353317
2       NaN -1.515640 -0.479633  1.718319
3       NaN  0.469202  0.761060  0.168241
4  0.678039  1.147087 -1.511676       NaN
5  1.997421  0.010971 -0.642358       NaN
6  0.200343 -1.243802  1.394458       NaN