In [1]:
import numpy as np

In [2]:
my_list1=[1,2,3,4]

In [3]:
my_list2=[5,6,7,8]

In [5]:
my_array1 = np.array(my_list1)

In [1]:
my_array1

NameError: name 'my_array1' is not defined

In [7]:
my_lists = [my_list1,my_list2]

In [8]:
my_lists


[[1, 2, 3, 4], [5, 6, 7, 8]]

In [9]:
my_multdArray = np.array(my_lists)

In [10]:
my_multdArray

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
my_multdArray.shape

(2, 4)

In [12]:
my_multdArray.dtype


dtype('int64')

In [16]:
my_array_zeros = np.zeros(5)

In [19]:
np.ones([3,3])

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [21]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [22]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [23]:
np.arange(1,5,2)

array([1, 3])

In [24]:
np.arange(1,5)

array([1, 2, 3, 4])