In [1]:
import numpy as np


In [3]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [4]:
from __future__ import division

In [7]:
array1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
array1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [8]:
array1*array1

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100]])

In [9]:
array1-array1


array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [10]:
1/array1

array([[ 1.        ,  0.5       ,  0.33333333,  0.25      ,  0.2       ],
       [ 0.16666667,  0.14285714,  0.125     ,  0.11111111,  0.1       ]])

In [11]:
array1 ** 2

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100]])